# Generated by Django 2.2.18 on 2021-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='classes_inner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='formpage',
            name='classes_outer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
