# Generated by Django 2.2.18 on 2021-04-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_postcollection_postsindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='social_heading',
            field=models.CharField(blank=True, default="We're social", max_length=140),
        ),
    ]
