# Generated by Django 2.2.18 on 2021-04-12 02:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_configuration_social_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='primary_color',
            new_name='primary_color_hex',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='secondary_color',
            new_name='secondary_color_hex',
        ),
        migrations.AddField(
            model_name='configuration',
            name='background_color_class',
            field=models.CharField(blank=True, default='w3-light-grey', max_length=15),
        ),
    ]
