# Generated by Django 2.2.18 on 2021-04-21 16:59

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
from django.db import migrations, models

import api.models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_remove_people_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('api', '0007_auto_20210412_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('pre_stream_body', wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock(
                    [('carousel_items', wagtail.core.blocks.ListBlock(api.models.HeroBlock))])), ('hero',
                                                                                                  wagtail.core.blocks.StructBlock(
                                                                                                      [('image',
                                                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                                                            required=False)),
                                                                                                       ('title',
                                                                                                        wagtail.core.blocks.CharBlock(
                                                                                                            required=True)),
                                                                                                       ('subtitle',
                                                                                                        wagtail.core.blocks.TextBlock(
                                                                                                            required=False)),
                                                                                                       ('height',
                                                                                                        wagtail.core.blocks.CharBlock(
                                                                                                            default='700px',
                                                                                                            required=True)),
                                                                                                       (
                                                                                                       'container_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-display-middle',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-display-left container',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-display-right container',
                                                                                                                    'Right')])),
                                                                                                       (
                                                                                                       'text_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-center',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-left-align',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-right-align',
                                                                                                                    'Right')],
                                                                                                           editable=False)),
                                                                                                       ('buttons',
                                                                                                        wagtail.core.blocks.ListBlock(
                                                                                                            api.models.ButtonBlock))])),
                                                                     ('introducer', wagtail.core.blocks.StructBlock([(
                                                                                                                     'classes',
                                                                                                                     wagtail.core.blocks.StructBlock(
                                                                                                                         [
                                                                                                                             (
                                                                                                                             'outer',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False)),
                                                                                                                             (
                                                                                                                             'inner',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False))])),
                                                                                                                     (
                                                                                                                     'image',
                                                                                                                     wagtail.core.blocks.StructBlock(
                                                                                                                         [
                                                                                                                             (
                                                                                                                             'image',
                                                                                                                             wagtail.images.blocks.ImageChooserBlock(
                                                                                                                                 required=False)),
                                                                                                                             (
                                                                                                                             'caption',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False)),
                                                                                                                             (
                                                                                                                             'attribution',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False)),
                                                                                                                             (
                                                                                                                             'dimensions',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False))])),
                                                                                                                     (
                                                                                                                     'image_position',
                                                                                                                     wagtail.core.blocks.ChoiceBlock(
                                                                                                                         blank=True,
                                                                                                                         choices=[
                                                                                                                             (
                                                                                                                             'left',
                                                                                                                             'Left'),
                                                                                                                             (
                                                                                                                             'right',
                                                                                                                             'Right')])),
                                                                                                                     (
                                                                                                                     'text',
                                                                                                                     wagtail.core.blocks.TextBlock(
                                                                                                                         required=False)),
                                                                                                                     (
                                                                                                                     'buttons',
                                                                                                                     wagtail.core.blocks.ListBlock(
                                                                                                                         api.models.ButtonBlock))])),
                                                                     ('grid_of_cards', wagtail.core.blocks.StructBlock([
                                                                                                                           (
                                                                                                                           'classes',
                                                                                                                           wagtail.core.blocks.StructBlock(
                                                                                                                               [
                                                                                                                                   (
                                                                                                                                   'outer',
                                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                                       required=False)),
                                                                                                                                   (
                                                                                                                                   'inner',
                                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                                       required=False))])),
                                                                                                                           (
                                                                                                                           'cards',
                                                                                                                           wagtail.core.blocks.ListBlock(
                                                                                                                               api.models.CardBlock))])),
                                                                     ('padding', wagtail.core.blocks.StructBlock([(
                                                                                                                  'size',
                                                                                                                  wagtail.core.blocks.IntegerBlock(
                                                                                                                      required=True))])),
                                                                     ('heading', wagtail.core.blocks.StructBlock([(
                                                                                                                  'classes',
                                                                                                                  wagtail.core.blocks.StructBlock(
                                                                                                                      [(
                                                                                                                       'outer',
                                                                                                                       wagtail.core.blocks.CharBlock(
                                                                                                                           required=False)),
                                                                                                                       (
                                                                                                                       'inner',
                                                                                                                       wagtail.core.blocks.CharBlock(
                                                                                                                           required=False))])),
                                                                                                                  (
                                                                                                                  'title',
                                                                                                                  wagtail.core.blocks.CharBlock(
                                                                                                                      required=True)),
                                                                                                                  (
                                                                                                                  'size',
                                                                                                                  wagtail.core.blocks.ChoiceBlock(
                                                                                                                      blank=True,
                                                                                                                      choices=[
                                                                                                                          (
                                                                                                                          '',
                                                                                                                          'Select a header size'),
                                                                                                                          (
                                                                                                                          'h2',
                                                                                                                          'H2'),
                                                                                                                          (
                                                                                                                          'h3',
                                                                                                                          'H3'),
                                                                                                                          (
                                                                                                                          'h4',
                                                                                                                          'H4')],
                                                                                                                      required=False)),
                                                                                                                  (
                                                                                                                  'subtitle',
                                                                                                                  wagtail.core.blocks.CharBlock(
                                                                                                                      required=False))])),
                                                                     ('paragraph', wagtail.core.blocks.StructBlock([(
                                                                                                                    'classes',
                                                                                                                    wagtail.core.blocks.StructBlock(
                                                                                                                        [
                                                                                                                            (
                                                                                                                            'outer',
                                                                                                                            wagtail.core.blocks.CharBlock(
                                                                                                                                required=False)),
                                                                                                                            (
                                                                                                                            'inner',
                                                                                                                            wagtail.core.blocks.CharBlock(
                                                                                                                                required=False))])),
                                                                                                                    (
                                                                                                                    'text',
                                                                                                                    wagtail.core.blocks.TextBlock(
                                                                                                                        required=False))])),
                                                                     ('embed', wagtail.embeds.blocks.EmbedBlock()), (
                                                                     'half_title_text', wagtail.core.blocks.StructBlock(
                                                                         [('heading', wagtail.core.blocks.StructBlock([(
                                                                                                                       'classes',
                                                                                                                       wagtail.core.blocks.StructBlock(
                                                                                                                           [
                                                                                                                               (
                                                                                                                               'outer',
                                                                                                                               wagtail.core.blocks.CharBlock(
                                                                                                                                   required=False)),
                                                                                                                               (
                                                                                                                               'inner',
                                                                                                                               wagtail.core.blocks.CharBlock(
                                                                                                                                   required=False))])),
                                                                                                                       (
                                                                                                                       'title',
                                                                                                                       wagtail.core.blocks.CharBlock(
                                                                                                                           required=True)),
                                                                                                                       (
                                                                                                                       'size',
                                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                                           blank=True,
                                                                                                                           choices=[
                                                                                                                               (
                                                                                                                               '',
                                                                                                                               'Select a header size'),
                                                                                                                               (
                                                                                                                               'h2',
                                                                                                                               'H2'),
                                                                                                                               (
                                                                                                                               'h3',
                                                                                                                               'H3'),
                                                                                                                               (
                                                                                                                               'h4',
                                                                                                                               'H4')],
                                                                                                                           required=False)),
                                                                                                                       (
                                                                                                                       'subtitle',
                                                                                                                       wagtail.core.blocks.CharBlock(
                                                                                                                           required=False))])),
                                                                          ('paragraph', wagtail.core.blocks.StructBlock(
                                                                              [('classes',
                                                                                wagtail.core.blocks.StructBlock([(
                                                                                                                 'outer',
                                                                                                                 wagtail.core.blocks.CharBlock(
                                                                                                                     required=False)),
                                                                                                                 (
                                                                                                                 'inner',
                                                                                                                 wagtail.core.blocks.CharBlock(
                                                                                                                     required=False))])),
                                                                               ('text', wagtail.core.blocks.TextBlock(
                                                                                   required=False))]))]))], blank=True,
                                                                    null=True)),
                ('post_stream_body', wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock(
                    [('carousel_items', wagtail.core.blocks.ListBlock(api.models.HeroBlock))])), ('hero',
                                                                                                  wagtail.core.blocks.StructBlock(
                                                                                                      [('image',
                                                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                                                            required=False)),
                                                                                                       ('title',
                                                                                                        wagtail.core.blocks.CharBlock(
                                                                                                            required=True)),
                                                                                                       ('subtitle',
                                                                                                        wagtail.core.blocks.TextBlock(
                                                                                                            required=False)),
                                                                                                       ('height',
                                                                                                        wagtail.core.blocks.CharBlock(
                                                                                                            default='700px',
                                                                                                            required=True)),
                                                                                                       (
                                                                                                       'container_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-display-middle',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-display-left container',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-display-right container',
                                                                                                                    'Right')])),
                                                                                                       (
                                                                                                       'text_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-center',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-left-align',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-right-align',
                                                                                                                    'Right')],
                                                                                                           editable=False)),
                                                                                                       ('buttons',
                                                                                                        wagtail.core.blocks.ListBlock(
                                                                                                            api.models.ButtonBlock))])),
                                                                      ('introducer', wagtail.core.blocks.StructBlock([(
                                                                                                                      'classes',
                                                                                                                      wagtail.core.blocks.StructBlock(
                                                                                                                          [
                                                                                                                              (
                                                                                                                              'outer',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  required=False)),
                                                                                                                              (
                                                                                                                              'inner',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  required=False))])),
                                                                                                                      (
                                                                                                                      'image',
                                                                                                                      wagtail.core.blocks.StructBlock(
                                                                                                                          [
                                                                                                                              (
                                                                                                                              'image',
                                                                                                                              wagtail.images.blocks.ImageChooserBlock(
                                                                                                                                  required=False)),
                                                                                                                              (
                                                                                                                              'caption',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  required=False)),
                                                                                                                              (
                                                                                                                              'attribution',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  required=False)),
                                                                                                                              (
                                                                                                                              'dimensions',
                                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                                  required=False))])),
                                                                                                                      (
                                                                                                                      'image_position',
                                                                                                                      wagtail.core.blocks.ChoiceBlock(
                                                                                                                          blank=True,
                                                                                                                          choices=[
                                                                                                                              (
                                                                                                                              'left',
                                                                                                                              'Left'),
                                                                                                                              (
                                                                                                                              'right',
                                                                                                                              'Right')])),
                                                                                                                      (
                                                                                                                      'text',
                                                                                                                      wagtail.core.blocks.TextBlock(
                                                                                                                          required=False)),
                                                                                                                      (
                                                                                                                      'buttons',
                                                                                                                      wagtail.core.blocks.ListBlock(
                                                                                                                          api.models.ButtonBlock))])),
                                                                      ('grid_of_cards', wagtail.core.blocks.StructBlock(
                                                                          [('classes', wagtail.core.blocks.StructBlock([
                                                                                                                           (
                                                                                                                           'outer',
                                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                                               required=False)),
                                                                                                                           (
                                                                                                                           'inner',
                                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                                               required=False))])),
                                                                           ('cards', wagtail.core.blocks.ListBlock(
                                                                               api.models.CardBlock))])), ('padding',
                                                                                                           wagtail.core.blocks.StructBlock(
                                                                                                               [('size',
                                                                                                                 wagtail.core.blocks.IntegerBlock(
                                                                                                                     required=True))])),
                                                                      ('heading', wagtail.core.blocks.StructBlock([(
                                                                                                                   'classes',
                                                                                                                   wagtail.core.blocks.StructBlock(
                                                                                                                       [
                                                                                                                           (
                                                                                                                           'outer',
                                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                                               required=False)),
                                                                                                                           (
                                                                                                                           'inner',
                                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                                               required=False))])),
                                                                                                                   (
                                                                                                                   'title',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=True)),
                                                                                                                   (
                                                                                                                   'size',
                                                                                                                   wagtail.core.blocks.ChoiceBlock(
                                                                                                                       blank=True,
                                                                                                                       choices=[
                                                                                                                           (
                                                                                                                           '',
                                                                                                                           'Select a header size'),
                                                                                                                           (
                                                                                                                           'h2',
                                                                                                                           'H2'),
                                                                                                                           (
                                                                                                                           'h3',
                                                                                                                           'H3'),
                                                                                                                           (
                                                                                                                           'h4',
                                                                                                                           'H4')],
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   'subtitle',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False))])),
                                                                      ('paragraph', wagtail.core.blocks.StructBlock([(
                                                                                                                     'classes',
                                                                                                                     wagtail.core.blocks.StructBlock(
                                                                                                                         [
                                                                                                                             (
                                                                                                                             'outer',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False)),
                                                                                                                             (
                                                                                                                             'inner',
                                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                                 required=False))])),
                                                                                                                     (
                                                                                                                     'text',
                                                                                                                     wagtail.core.blocks.TextBlock(
                                                                                                                         required=False))])),
                                                                      ('embed', wagtail.embeds.blocks.EmbedBlock()), (
                                                                      'half_title_text',
                                                                      wagtail.core.blocks.StructBlock([('heading',
                                                                                                        wagtail.core.blocks.StructBlock(
                                                                                                            [('classes',
                                                                                                              wagtail.core.blocks.StructBlock(
                                                                                                                  [(
                                                                                                                   'outer',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   'inner',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False))])),
                                                                                                             ('title',
                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                  required=True)),
                                                                                                             ('size',
                                                                                                              wagtail.core.blocks.ChoiceBlock(
                                                                                                                  blank=True,
                                                                                                                  choices=[
                                                                                                                      (
                                                                                                                      '',
                                                                                                                      'Select a header size'),
                                                                                                                      (
                                                                                                                      'h2',
                                                                                                                      'H2'),
                                                                                                                      (
                                                                                                                      'h3',
                                                                                                                      'H3'),
                                                                                                                      (
                                                                                                                      'h4',
                                                                                                                      'H4')],
                                                                                                                  required=False)),
                                                                                                             (
                                                                                                             'subtitle',
                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                 required=False))])),
                                                                                                       ('paragraph',
                                                                                                        wagtail.core.blocks.StructBlock(
                                                                                                            [('classes',
                                                                                                              wagtail.core.blocks.StructBlock(
                                                                                                                  [(
                                                                                                                   'outer',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   'inner',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False))])),
                                                                                                             ('text',
                                                                                                              wagtail.core.blocks.TextBlock(
                                                                                                                  required=False))]))]))],
                                                                     blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPage',
            fields=[
                ('page_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('introduction', models.TextField(blank=True, help_text='Text to describe the page')),
                ('body', wagtail.core.fields.StreamField([('heading_block', wagtail.core.blocks.StructBlock([('classes',
                                                                                                              wagtail.core.blocks.StructBlock(
                                                                                                                  [(
                                                                                                                   'outer',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False)),
                                                                                                                   (
                                                                                                                   'inner',
                                                                                                                   wagtail.core.blocks.CharBlock(
                                                                                                                       required=False))])),
                                                                                                             ('title',
                                                                                                              wagtail.core.blocks.CharBlock(
                                                                                                                  required=True)),
                                                                                                             ('size',
                                                                                                              wagtail.core.blocks.ChoiceBlock(
                                                                                                                  blank=True,
                                                                                                                  choices=[
                                                                                                                      (
                                                                                                                      '',
                                                                                                                      'Select a header size'),
                                                                                                                      (
                                                                                                                      'h2',
                                                                                                                      'H2'),
                                                                                                                      (
                                                                                                                      'h3',
                                                                                                                      'H3'),
                                                                                                                      (
                                                                                                                      'h4',
                                                                                                                      'H4')],
                                                                                                                  required=False)),
                                                                                                             (
                                                                                                             'subtitle',
                                                                                                             wagtail.core.blocks.CharBlock(
                                                                                                                 required=False))])),
                                                          ('paragraph_block',
                                                           wagtail.core.blocks.RichTextBlock(icon='fa-paragraph')), (
                                                          'image_block', wagtail.core.blocks.StructBlock([('image',
                                                                                                           wagtail.images.blocks.ImageChooserBlock(
                                                                                                               required=False)),
                                                                                                          ('caption',
                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                               required=False)),
                                                                                                          (
                                                                                                          'attribution',
                                                                                                          wagtail.core.blocks.CharBlock(
                                                                                                              required=False)),
                                                                                                          ('dimensions',
                                                                                                           wagtail.core.blocks.CharBlock(
                                                                                                               required=False))])),
                                                          ('block_quote', wagtail.core.blocks.StructBlock(
                                                              [('text', wagtail.core.blocks.TextBlock()), (
                                                              'attribute_name',
                                                              wagtail.core.blocks.CharBlock(blank=True,
                                                                                            label='e.g. Mary Berry',
                                                                                            required=False))])), (
                                                          'embed_block', wagtail.embeds.blocks.EmbedBlock(
                                                              help_text='Insert an embed URL e.g https://www.youtube.com/embed/SGJFWirQ3ks',
                                                              icon='fa-s15', template='blocks/embed_block.html'))],
                                                         blank=True, verbose_name='Page body')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('date_published', models.DateField(blank=True, null=True, verbose_name='Date article published')),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.ForeignKey(blank=True,
                                            help_text='Landscape mode only; horizontal width between 1000px and 3000px.',
                                            null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                            to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                                   related_name='tagged_items', to='api.BlogPage')),
                ('tag',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_blogpagetag_items',
                                   to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPeopleRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE,
                                                         related_name='blog_person_relationship', to='api.BlogPage')),
                ('people',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_blog_relationship',
                                   to='accounts.People')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='youtube',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SelassieMensahIndex',
            fields=[
                ('blogindexpage_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='api.BlogIndexPage')),
                ('about_me_text', models.TextField(blank=True)),
                ('about_me_image',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                   related_name='+', to='wagtailimages.Image')),
                ('about_me_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                    related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('api.blogindexpage',),
        ),
        migrations.DeleteModel(
            name='PostsIndexPage',
        ),
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True,
                                                                     help_text='A comma-separated list of tags.',
                                                                     through='api.BlogPageTag', to='taggit.Tag',
                                                                     verbose_name='Tags'),
        ),
    ]
