# Generated by Django 2.2.18 on 2021-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0008_auto_20210421_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='show_site_name',
            field=models.BooleanField(default=True),
        ),
    ]
