# Generated by Django 2.2.18 on 2021-04-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0010_selassiemensahindex_more_posts_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='extra_head_content',
            field=models.TextField(blank=True),
        ),
    ]
