# Generated by Django 2.2.18 on 2021-04-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0012_documentspage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentspage',
            name='documents',
            field=models.ManyToManyField(blank=True, to='wagtaildocs.Document'),
        ),
    ]
