# Generated by Django 2.2.18 on 2021-04-24 07:35

import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0013_auto_20210424_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentspage',
            name='documents',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='wagtaildocs.Document'),
        ),
    ]
