# Generated by Django 2.2.18 on 2021-04-10 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20210410_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='title',
        ),
    ]
