# Generated by Django 2.2.18 on 2021-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0002_auto_20210404_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='font_size',
            field=models.IntegerField(blank=True, default=1, max_length=15),
            preserve_default=False,
        ),
    ]
