# Generated by Django 2.2.18 on 2021-03-31 11:05

from django.db import migrations, models
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210331_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock, template='blocks/carousel.html')), ('hero', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, verbose_name='Page body'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True, help_text='Text to describe the page'),
        ),
    ]
