# Generated by Django 2.2.18 on 2021-04-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0003_configuration_font_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='font_size',
            field=models.IntegerField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
