# Generated by Django 2.2.18 on 2021-04-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_auto_20210404_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='font_size',
            field=models.CharField(blank=True, default=1, max_length=15, null=True),
        ),
    ]
