# Generated by Django 2.2.18 on 2021-03-31 11:06

from django.db import migrations
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210331_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock, template='blocks/carousel.html')), ('hero', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False))]))], blank=True, null=True, verbose_name='Page body'),
        ),
    ]
