# Generated by Django 2.2.18 on 2021-04-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0005_auto_20210404_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='youtube',
        ),
        migrations.AddField(
            model_name='configuration',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='instagram',
            field=models.URLField(blank=True),
        ),
    ]
