# Generated by Django 2.2.18 on 2021-03-31 11:37

from django.db import migrations
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210331_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock, template='blocks/carousel.html')), ('hero', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False)), ('container_classes', wagtail.core.blocks.CharBlock(default='w3-display-middle', required=False)), ('text_alignment', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('w3-left-align', 'Left aligned'), ('w3-center', 'Center'), ('w3-right-align', 'Right aligned')]))]))], blank=True, null=True, verbose_name='Page body'),
        ),
    ]
