# Generated by Django 2.2.18 on 2021-03-31 11:53

from django.db import migrations
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210331_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock, template='blocks/carousel.html')), ('hero', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False)), ('alignment', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('center', 'Center'), ('left', 'Left'), ('right', 'Right')]))]))], blank=True, null=True, verbose_name='Page body'),
        ),
    ]
