# Generated by Django 2.2.18 on 2021-04-04 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('home', '0006_auto_20210404_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='+', to='wagtailimages.Image'),
        ),
    ]
