# Generated by Django 2.2.18 on 2021-04-01 11:49

from django.db import migrations
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210331_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock, template='blocks/carousel.html')), ('hero', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False)), ('container_alignment', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('w3-display-middle', 'Center'), ('w3-display-left container', 'Left'), ('w3-display-right container', 'Right')])), ('text_alignment', wagtail.core.blocks.ChoiceBlock(blank=True, choices=[('w3-center', 'Center'), ('w3-left-align', 'Left'), ('w3-right-align', 'Right')], editable=False)), ('buttons', wagtail.core.blocks.ListBlock(sedesel.blocks.ButtonBlock))])), ('brief_section_introducer', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(required=True)), ('text', wagtail.core.blocks.TextBlock(max_length=450, required=False)), ('buttons', wagtail.core.blocks.ListBlock(sedesel.blocks.ButtonBlock))])), ('grid_of_cards', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('subtitle', wagtail.core.blocks.TextBlock(required=False)), ('container_class', wagtail.core.blocks.CharBlock()), ('cards', wagtail.core.blocks.ListBlock(sedesel.blocks.CardBlock))]))], blank=True, null=True, verbose_name='Page body'),
        ),
    ]
