# Generated by Django 2.2.18 on 2021-04-01 12:03

from django.db import migrations, models
import sedesel.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0008_auto_20210401_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='body',
            field=wagtail.core.fields.StreamField([('carousel', wagtail.core.blocks.StructBlock(
                [('carousel_items', wagtail.core.blocks.ListBlock(sedesel.blocks.HeroBlock))])), ('hero',
                                                                                                  wagtail.core.blocks.StructBlock(
                                                                                                      [('image',
                                                                                                        wagtail.images.blocks.ImageChooserBlock(
                                                                                                            required=False)),
                                                                                                       ('title',
                                                                                                        wagtail.core.blocks.CharBlock(
                                                                                                            required=True)),
                                                                                                       ('subtitle',
                                                                                                        wagtail.core.blocks.TextBlock(
                                                                                                            required=False)),
                                                                                                       (
                                                                                                       'container_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-display-middle',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-display-left container',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-display-right container',
                                                                                                                    'Right')])),
                                                                                                       (
                                                                                                       'text_alignment',
                                                                                                       wagtail.core.blocks.ChoiceBlock(
                                                                                                           blank=True,
                                                                                                           choices=[(
                                                                                                                    'w3-center',
                                                                                                                    'Center'),
                                                                                                                    (
                                                                                                                    'w3-left-align',
                                                                                                                    'Left'),
                                                                                                                    (
                                                                                                                    'w3-right-align',
                                                                                                                    'Right')],
                                                                                                           editable=False)),
                                                                                                       ('buttons',
                                                                                                        wagtail.core.blocks.ListBlock(
                                                                                                            sedesel.blocks.ButtonBlock))])),
                                                   ('introducer', wagtail.core.blocks.StructBlock([('image',
                                                                                                    wagtail.images.blocks.ImageChooserBlock(
                                                                                                        required=False)),
                                                                                                   ('title',
                                                                                                    wagtail.core.blocks.CharBlock(
                                                                                                        required=True)),
                                                                                                   ('text',
                                                                                                    wagtail.core.blocks.TextBlock(
                                                                                                        max_length=450,
                                                                                                        required=False)),
                                                                                                   ('buttons',
                                                                                                    wagtail.core.blocks.ListBlock(
                                                                                                        sedesel.blocks.ButtonBlock))])),
                                                   ('grid_of_cards', wagtail.core.blocks.StructBlock(
                                                       [('title', wagtail.core.blocks.CharBlock(required=True)),
                                                        ('subtitle', wagtail.core.blocks.TextBlock(required=False)),
                                                        ('container_class', wagtail.core.blocks.CharBlock()), ('cards',
                                                                                                               wagtail.core.blocks.ListBlock(
                                                                                                                   sedesel.blocks.CardBlock))])),
                                                   ('heading', wagtail.core.blocks.StructBlock([('heading_text',
                                                                                                 wagtail.core.blocks.CharBlock(
                                                                                                     classname='title',
                                                                                                     required=True)), (
                                                                                                'size',
                                                                                                wagtail.core.blocks.ChoiceBlock(
                                                                                                    blank=True,
                                                                                                    choices=[('',
                                                                                                              'Select a header size'),
                                                                                                             ('h2',
                                                                                                              'H2'), (
                                                                                                             'h3',
                                                                                                             'H3'), (
                                                                                                             'h4',
                                                                                                             'H4')],
                                                                                                    required=False))])),
                                                   ('paragraph', wagtail.core.blocks.StructBlock(
                                                       [('paragraph', wagtail.core.blocks.RichTextBlock())])),
                                                   ('embed_block', wagtail.embeds.blocks.EmbedBlock())], blank=True,
                                                  null=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
    ]
