# Generated by Django 2.2.18 on 2021-04-05 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0009_auto_20210405_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='groupings',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True,
                                                            null=True, size=None),
        ),
    ]
