# Generated by Django 2.2.18 on 2021-04-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0010_formpage_groupings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='groupings',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
