# Generated by Django 2.2.18 on 2021-04-10 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0012_peoplepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peoplepage',
            name='introduction',
        ),
    ]
