# Generated by Django 2.2.18 on 2021-04-10 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0013_remove_peoplepage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplepage',
            name='classes_inner',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='peoplepage',
            name='classes_outer',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
