# Generated by Django 2.2.18 on 2021-04-02 21:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0016_auto_20210402_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favicon',
            name='title',
        ),
    ]
