# Generated by Django 2.2.18 on 2021-04-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0017_remove_favicon_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='address_1',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='configuration',
            name='address_2',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='configuration',
            name='city',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='configuration',
            name='country',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
